---
# - name: Create directory for backend
#   file:
#     path: /home/ubuntu/backend/
#     state: directory

- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "copy backend file"
  become: true
  copy:
    src: /root/project/backend
    dest: /root
    force: no

- name: "install npm packages"
  become: true
  command: npm install
  args:
    chdir: /root/backend

- name: "compile npm packages"
  become: true
  command: npm run build
  args:
    chdir: /root/backend

- name: "start server"
  become: true
  command: pm2 start npm -- run start
  args:
    chdir: /root/backend/dist
# - name: Copy backend files
#   become: yes
#   synchronize:
#     src: ../../backend
#     dest: /home/ubuntu
#     recursive: true

# # - name: Copy backend files
# #   become: yes
# #   synchronize:
# #     src: ../../backend/dist
# #     dest: /home/ubuntu/backend
# #     recursive: true

# # - name: Copy backend modules
# #   become: yes
# #   synchronize:
# #     src: ../../backend/node_modules
# #     dest: /home/ubuntu/backend
# #     recursive: true

# - name: Start server
#   become: true
#   command: pm2 start npm -- run start
#   args:
#     chdir: /home/ubuntu/backend
